Display the section without insulators and for simple supports
phlowers/mechaphlowers pull request #41
Opened 2024-12-23 17:13 UTC by adriengoeller

**Please check if the PR fulfills these requirements**

- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

Fixes #40 
#15 is now full-solved:
- Take a SectionArray object:
  - [X] get supports points coordinates matrix
  - [x] get insulator points coordinates matrix
  - [X] get cable points
- Take a plotly figure object
  - [X] plot support with (style, color) of support
  - [x] plot insulator with (style, color) of insulator
  - [X] plot cable points with (style, color) of cable
- [x] Select span or spans to plot (one span = left support, insulators, cable and right support)

**What kind of change does this PR introduce?**

feature

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [X] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *breaking change* or *deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-12-31 07:14 UTC, annetill commented on test/entities/test_frames.py
> +import numpy as np
Copyright missing.

2024-12-31 07:15 UTC, annetill commented on src/mechaphlowers/core/geometry/references.py
> +from typing import Tuple
Copyright missing.

2025-01-08 14:04 UTC, ai-qui commented on test/plotting/test_line3d.py
> +    assert True
Just a passing thought: I suggest adding similar instructions (in a later PR, if and when we have time) in a jupyter notebook :)

2025-01-09 12:07 UTC, adriengoeller commented on test/plotting/test_line3d.py
> +    assert True
Good idea !

2025-01-09 18:02 UTC, yousza requested changes

2025-01-09 18:38 UTC, yousza approved these changes

2025-01-09 18:58 UTC, merged